# Generated by Django 4.0.5 on 2023-02-14 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='id_Trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.trabajador'),
        ),
    ]
