# Generated by Django 4.0.5 on 2023-02-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_usuarios_id_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comercial', models.CharField(max_length=100)),
                ('Razon_Social', models.CharField(max_length=250)),
                ('Ruc', models.CharField(max_length=13)),
                ('Contabilidad', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='H_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='rol',
            name='Descripcion',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sucursal', models.CharField(max_length=3)),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=10)),
                ('Correo', models.CharField(max_length=100)),
                ('id_Empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.empresa')),
            ],
        ),
    ]
