# Generated by Django 4.0.5 on 2023-03-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_empresa_h_login_alter_rol_descripcion_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferreteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.DeleteModel(
            name='H_Login',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='id_Empresa',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_Rol',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_Trabajador',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
