# Generated by Django 4.0.5 on 2023-03-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_ferreteria_delete_h_login_remove_sucursal_id_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferreteria',
            old_name='Imagen',
            new_name='imagen',
        ),
    ]
