# Generated by Django 4.0.5 on 2023-03-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario1', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=50)),
                ('repepaswor', models.CharField(max_length=50)),
                ('emagi', models.EmailField(max_length=254)),
            ],
        ),
    ]
