# Generated by Django 4.1.7 on 2023-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferreteria',
            name='marca',
            field=models.CharField(default=1, max_length=50, verbose_name='Marca'),
            preserve_default=False,
        ),
    ]
